mark2cure/talk/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [

    url(r'^(?P<document_pk>\d+)/$',
        views.home, name='home'),

    url(r'^annotation/$',
        views.annotation_search, name='annotation-search'),

    url(r'',
        views.recent_discussion, name='recent'),

]

mark2cure/urls.py
from django.conf.urls import include, url

from django.contrib import admin
from django.contrib.flatpages import views
from django.contrib.auth import views as reset_views

from django.contrib.sitemaps import Sitemap
from django.contrib.sitemaps.views import sitemap
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.urls import reverse

from django.contrib.auth.models import User
from mark2cure.common.models import Group
from mark2cure.userprofile.models import Team


class FlatPages(FlatPageSitemap):
    protocol = 'https'
    priority = 1.0
    changefreq = 'monthly'


class QuestDetails(Sitemap):
    protocol = 'https'
    priority = 1.0
    changefreq = 'weekly'

    def items(self):
        return Group.objects.values_list('stub', flat=True)

    def location(self, item):
        return reverse('common:ner-group-home', kwargs={'group_stub': item})


class UserDetails(Sitemap):
    protocol = 'https'
    priority = .5
    changefreq = 'weekly'

    def items(self):
        return User.objects.values_list('username', flat=True)

    def location(self, item):
        return reverse('profile:public-profile', kwargs={'username': item})


class TeamDetails(Sitemap):
    protocol = 'https'
    priority = .6
    changefreq = 'weekly'

    def items(self):
        return Team.objects.values_list('slug', flat=True)

    def location(self, item):
        return reverse('team:home', kwargs={'slug': item})


sitemaps = {
    'flatpages': FlatPages,
    'quest_detail': QuestDetails,
    'user_detail': UserDetails,
    'team_detail': TeamDetails
}

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    # url(r'^robots\.txt', include('robots.urls')),

    # Password / Account based changes
    url(r'^accounts/', include('mark2cure.userprofile.providers.zooniverse.urls')),
    url(r'^accounts/', include('allauth.urls')),

    # Response / Confirm Changes
    url(r'^reset/done/$',
        reset_views.password_reset_complete,
        {'template_name': 'password-reset/password_reset_complete.html'},
        name='reset'),

    url(r'^reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        reset_views.password_reset_confirm,
        {'template_name': 'password-reset/password_reset_confirm.html',
         'post_reset_redirect': '/reset/done/'},
        name='password_reset_confirm'),

    url(r'', include('mark2cure.common.urls',
        namespace='common')),

    url(r'^api/', include('mark2cure.api.urls',
        namespace='api')),

    url(r'^download/', include('mark2cure.download.urls',
        namespace='download')),

    url(r'^instructions/', include('mark2cure.instructions.urls',
        namespace='instructions')),
    url(r'^training/', include('mark2cure.training.urls',
        namespace='training')),


    # Task Section
    url(r'^task/ner/', include('mark2cure.task.ner.urls',
        namespace='task-ner')),

    url(r'^task/re/', include('mark2cure.task.re.urls',
        namespace='task-re')),

    url(r'^talk/', include('mark2cure.talk.urls',
        namespace='talk')),

    url(r'^team/', include('mark2cure.team.urls',
        namespace='team', app_name='team')),
    url(r'^u/', include('mark2cure.userprofile.urls',
        namespace='profile', app_name='userprofile')),


    url('', include('django.contrib.auth.urls', namespace='auth')),

    url(r'^comments/', include('django_comments.urls')),

    url(r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')),

    url(r'^(?P<url>.*/)$', views.flatpage),

]

mark2cure/talk/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.template.response import TemplateResponse
from django.shortcuts import get_object_or_404

from .decorators import doc_completion_required
from ..document.models import Document
from ..task.ner.models import EntityRecognitionAnnotation

from collections import Counter


@login_required
@doc_completion_required
def home(request, document_pk):
    document = get_object_or_404(Document, pk=document_pk)
    return TemplateResponse(request, 'talk/home.html', {'document': document})


@login_required
def annotation_search(request):
    annotation = request.GET.get('q')
    completed_document_pks = request.user.profile.completed_document_pks()

    # (TODO) Sanitize search param for RAW SQL
    content_type_id = str(ContentType.objects.get_for_model(EntityRecognitionAnnotation.objects.all().first()).id)
    document_pks = EntityRecognitionAnnotation.objects.document_pks_by_text_and_document_pks(annotation, completed_document_pks, content_type_id)

    documents = [(group[1], Document.objects.get(pk=group[0])) for group in Counter(document_pks).most_common()]
    ctx = {
        'annotation': annotation,
        'documents': documents
    }
    return TemplateResponse(request, 'talk/annotation_search.html', ctx)


@login_required
def recent_discussion(request):
    return TemplateResponse(request, 'talk/recent_discussion.html')

mark2cure/talk/templates/talk/annotation_search.html
{% extends "base.html" %}

{% load as_vertical_form from bootstrap %}
{% load widget_tweaks %}
{% load comments %}
{% load humanize %}

{% block header %}
<nav role='navigation' class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <h3>
          <a href="javascript:window.open('','_self').close();"><i class="fa fa-angle-double-left"></i> Back to Marking</a>
        </h3>
      </div>
    </div>
  </div>
</nav>
{% endblock %}

{% block content %}
<div class="container content">
  <div class="row">
    <div class="col-10">
      <h2 class="text-center"> #{annotation}</h2>
      <p class="lead text-center">This annotation also appeared in the following docs that you've marked. Help uncover more docs with this annotation by completing more quests!</p>

      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Annotation Occurances</th>
            <th>PMID</th>
            <th>Document</th>
          </tr>
        </thead>

        <tbody>
          {% for doc in documents %}
          <tr>
            <th scope="row"> #{doc.0}</th>
            <td>
              <a href='http://www.ncbi.nlm.nih.gov/pubmed/{{doc.1.document_id}}' target='_blank'>
                {{doc.1.document_id}}
              </a>
            </td>
            <td>
              <a href='{% url "talk:home" doc.1.document_id %}'>
                {{ doc.1.title }}
              </a>
            </td>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

mark2cure/talk/templates/talk/home.html
{% extends "base.html" %}

{% load as_vertical_form from bootstrap %}
{% load widget_tweaks %}
{% load comments %}


{% block header %}
  {% with headerMessage='Talk Page' %}
  {% include "includes/header.html" %}
  {% endwith %}
{% endblock header %}


{% block content %}
<div id="talk-document-home" class="container"></div>
{% endblock %}


{% block post-footer %}
<script>
  var TalkDocumentApp = Backbone.Marionette.Application.extend({
    region: '#talk-document-home',

    onStart: function() {
      var main = this.getRegion();
      main.show( new TalkDocumentView({'document_pk': {{document.pk}}}));
    }
  });
  var talk_document_app = new TalkDocumentApp();
  talk_document_app.start();
</script>
{% endblock %}

mark2cure/talk/templates/talk/recent_discussion.html
{% extends "base.html" %}

{% load as_vertical_form from bootstrap %}
{% load widget_tweaks %}
{% load comments %}


{% block header %}
  {% with headerMessage='Talk Pages' %}
  {% include "includes/header.html" %}
  {% endwith %}
{% endblock %}


{% block content %}
<div id="talk" class="container-fluid"></div>
{% endblock %}


{% block post-footer %}
<script>
  var TalkApp = Backbone.Marionette.Application.extend({
    region: '#talk',

    onStart: function() {
      var main = this.getRegion();
      main.show( new TalkView() );
    }
  });
  var talk_app = new TalkApp();
  talk_app.start();
</script>
{% endblock %}