mark2cure/download/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^$',
        views.home, name='home'),

    url(r'^export/$',
        views.start_export, name='export')

]

mark2cure/urls.py
from django.conf.urls import include, url

from django.contrib import admin
from django.contrib.flatpages import views
from django.contrib.auth import views as reset_views

from django.contrib.sitemaps import Sitemap
from django.contrib.sitemaps.views import sitemap
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.urls import reverse

from django.contrib.auth.models import User
from mark2cure.common.models import Group
from mark2cure.userprofile.models import Team


class FlatPages(FlatPageSitemap):
    protocol = 'https'
    priority = 1.0
    changefreq = 'monthly'


class QuestDetails(Sitemap):
    protocol = 'https'
    priority = 1.0
    changefreq = 'weekly'

    def items(self):
        return Group.objects.values_list('stub', flat=True)

    def location(self, item):
        return reverse('common:ner-group-home', kwargs={'group_stub': item})


class UserDetails(Sitemap):
    protocol = 'https'
    priority = .5
    changefreq = 'weekly'

    def items(self):
        return User.objects.values_list('username', flat=True)

    def location(self, item):
        return reverse('profile:public-profile', kwargs={'username': item})


class TeamDetails(Sitemap):
    protocol = 'https'
    priority = .6
    changefreq = 'weekly'

    def items(self):
        return Team.objects.values_list('slug', flat=True)

    def location(self, item):
        return reverse('team:home', kwargs={'slug': item})


sitemaps = {
    'flatpages': FlatPages,
    'quest_detail': QuestDetails,
    'user_detail': UserDetails,
    'team_detail': TeamDetails
}

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    # url(r'^robots\.txt', include('robots.urls')),

    # Password / Account based changes
    url(r'^accounts/', include('mark2cure.userprofile.providers.zooniverse.urls')),
    url(r'^accounts/', include('allauth.urls')),

    # Response / Confirm Changes
    url(r'^reset/done/$',
        reset_views.password_reset_complete,
        {'template_name': 'password-reset/password_reset_complete.html'},
        name='reset'),

    url(r'^reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        reset_views.password_reset_confirm,
        {'template_name': 'password-reset/password_reset_confirm.html',
         'post_reset_redirect': '/reset/done/'},
        name='password_reset_confirm'),

    url(r'', include('mark2cure.common.urls',
        namespace='common')),

    url(r'^api/', include('mark2cure.api.urls',
        namespace='api')),

    url(r'^download/', include('mark2cure.download.urls',
        namespace='download')),

    url(r'^instructions/', include('mark2cure.instructions.urls',
        namespace='instructions')),
    url(r'^training/', include('mark2cure.training.urls',
        namespace='training')),


    # Task Section
    url(r'^task/ner/', include('mark2cure.task.ner.urls',
        namespace='task-ner')),

    url(r'^task/re/', include('mark2cure.task.re.urls',
        namespace='task-re')),

    url(r'^talk/', include('mark2cure.talk.urls',
        namespace='talk')),

    url(r'^team/', include('mark2cure.team.urls',
        namespace='team', app_name='team')),
    url(r'^u/', include('mark2cure.userprofile.urls',
        namespace='profile', app_name='userprofile')),


    url('', include('django.contrib.auth.urls', namespace='auth')),

    url(r'^comments/', include('django_comments.urls')),

    url(r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')),

    url(r'^(?P<url>.*/)$', views.flatpage),

]

mark2cure/download/models.py
from django.db import models
import os

app_path = 'download/'


def _download_file_name(instance, filename, folder=app_path + 'data/bioc'):
    name = os.urandom(40).encode('hex') + os.path.splitext(filename)[1]
    return '/'.join([folder, name])


class Download(models.Model):
    documents = models.ManyToManyField('document.Document')

    task_er = models.BooleanField(default=False)
    task_rel = models.BooleanField(default=False)

    file = models.FileField(upload_to=_download_file_name, null=True, blank=True)

    create_time = models.DateTimeField(auto_now_add=True)

    download_count = models.IntegerField(default=0)

    class Meta:
        app_label = 'download'

mark2cure/download/views.py
from django.template.response import TemplateResponse
from ..common.models import Group
from ..task.re.models import RelationGroup
from django.views.decorators.http import require_http_methods
from django.shortcuts import redirect

from .models import Download
from .tasks import group_export


def home(request):
    groups = [(x[0], x[1], 'er') for x in Group.objects.values_list('pk', 'name')] + [(x[0], x[1], 'rel') for x in RelationGroup.objects.values_list('pk', 'name')]
    ctx = {
        'groups': groups,
        'downloads': Download.objects.all()
    }
    return TemplateResponse(request, 'download/home.html', ctx)


@require_http_methods(['POST'])
def start_export(request):
    task_type = request.POST.get('task_type')
    group_pk = request.POST.get('group_pk')
    document_pks = request.POST.get('document_pks')
    ALL = 0
    NER = 1
    RE = 2

    if task_type == 'ner':
        group = Group.objects.get(pk=group_pk)
        docs = group.get_documents()
        group_export.apply_async(
            args=[list(docs.values_list('pk', flat=True))],
            kwargs={'export_type': NER},
            queue='mark2cure_downloads')

    elif task_type == 're':
        group = RelationGroup.objects.get(pk=group_pk)
        docs = group.documents.all()
        group_export.apply_async(
            args=[list(docs.values_list('pk', flat=True))],
            kwargs={'export_type': RE},
            queue='mark2cure_downloads')

    else:
        group_export.apply_async(
            args=[document_pks],
            kwargs={'export_type': ALL},
            queue='mark2cure_downloads')

    return redirect('download:home')

mark2cure/download/templates/download/home.html
{% extends "base.html" %}
{% load humanize %}

{% block header %}
{% with headerMessage='Downloads' %}
{% include "includes/header.html" %}
{% endwith %}
{% endblock %}

{% block content %}
<div id="instructions" class="container m-t-1 m-b-2">

  <div class="row">
    <ol class="breadcrumb">
      <li><a href="{% url "instructions:home" %}">Instructions</a>
      </li>
      <!--block breadcrumb-->
    </ol>
  </div>

  <div class="row">
    <!-- Sidebar-->
    <div class="col-md-4">
      <ul class="list-group">

        {% for group in groups %}
        <li class="list-group-item row">
          <div class="col-xs-2">{% if  group.2 == 'er' %}<i aria-hidden="true" class="fa fa-pencil"></i>{% else %}<i aria-hidden="true" class="fa fa-share-alt"></i>{% endif %}
          </div>
          <div class="col-xs-10">
            <form method="post" action="{% url "download:export" %}">{%  csrf_token %}
              <input name="group_pk" type="hidden" value="{{ group.0 }}"/>
              <input name="task_type" type="hidden" value="{{ group.2 }}"/>
              <button type="submit" class="btn btn-link">{{group.1|escape}}</button>
            </form>
          </div>
        </li>
        {% endfor %}

      </ul>
    </div>
    <div class="col-md-8">
      <p class="lead text-xs-center m-t-2">Here is your resource to be able to download the raw data collected by Mark2Cure</p>
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>ER</th>
            <th>Rel</th>
            <th>Generated</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {% for download in downloads %}
          <tr>
            <th scope="row">{{forloop.counter|escape}}</th>
            <th></th>
            <th>{% if download.task_er %}<i aria-hidden="true" class="fa fa-check"></i>{% else %}<i aria-hidden="true" class="fa fa-times"></i>{% endif %}</th>
            <th>{% if download.task_rel %}<i aria-hidden="true" class="fa fa-check"></i>{% else %}<i aria-hidden="true" class="fa fa-times"></i>{% endif %}</th>
            <th>{{download.create_time|naturaltime|escape}}</th>
            <th>{% if download.file %}<a href="{{ download.file.url }}" target="_blank">
                <p>Download</p></a>{% else %}<i aria-hidden="true" class="fa fa-spinner"></i>{% endif %}
            </th>
          </tr>
          {% endfor %}

        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}