mark2cure/team/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<slug>[\w.@+-]+)/',
        views.home, name='home'),
]

mark2cure/urls.py
from django.conf.urls import include, url

from django.contrib import admin
from django.contrib.flatpages import views
from django.contrib.auth import views as reset_views

from django.contrib.sitemaps import Sitemap
from django.contrib.sitemaps.views import sitemap
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.urls import reverse

from django.contrib.auth.models import User
from mark2cure.common.models import Group
from mark2cure.userprofile.models import Team


class FlatPages(FlatPageSitemap):
    protocol = 'https'
    priority = 1.0
    changefreq = 'monthly'


class QuestDetails(Sitemap):
    protocol = 'https'
    priority = 1.0
    changefreq = 'weekly'

    def items(self):
        return Group.objects.values_list('stub', flat=True)

    def location(self, item):
        return reverse('common:ner-group-home', kwargs={'group_stub': item})


class UserDetails(Sitemap):
    protocol = 'https'
    priority = .5
    changefreq = 'weekly'

    def items(self):
        return User.objects.values_list('username', flat=True)

    def location(self, item):
        return reverse('profile:public-profile', kwargs={'username': item})


class TeamDetails(Sitemap):
    protocol = 'https'
    priority = .6
    changefreq = 'weekly'

    def items(self):
        return Team.objects.values_list('slug', flat=True)

    def location(self, item):
        return reverse('team:home', kwargs={'slug': item})


sitemaps = {
    'flatpages': FlatPages,
    'quest_detail': QuestDetails,
    'user_detail': UserDetails,
    'team_detail': TeamDetails
}

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    # url(r'^robots\.txt', include('robots.urls')),

    # Password / Account based changes
    url(r'^accounts/', include('mark2cure.userprofile.providers.zooniverse.urls')),
    url(r'^accounts/', include('allauth.urls')),

    # Response / Confirm Changes
    url(r'^reset/done/$',
        reset_views.password_reset_complete,
        {'template_name': 'password-reset/password_reset_complete.html'},
        name='reset'),

    url(r'^reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        reset_views.password_reset_confirm,
        {'template_name': 'password-reset/password_reset_confirm.html',
         'post_reset_redirect': '/reset/done/'},
        name='password_reset_confirm'),

    url(r'', include('mark2cure.common.urls',
        namespace='common')),

    url(r'^api/', include('mark2cure.api.urls',
        namespace='api')),

    url(r'^download/', include('mark2cure.download.urls',
        namespace='download')),

    url(r'^instructions/', include('mark2cure.instructions.urls',
        namespace='instructions')),
    url(r'^training/', include('mark2cure.training.urls',
        namespace='training')),


    # Task Section
    url(r'^task/ner/', include('mark2cure.task.ner.urls',
        namespace='task-ner')),

    url(r'^task/re/', include('mark2cure.task.re.urls',
        namespace='task-re')),

    url(r'^talk/', include('mark2cure.talk.urls',
        namespace='talk')),

    url(r'^team/', include('mark2cure.team.urls',
        namespace='team', app_name='team')),
    url(r'^u/', include('mark2cure.userprofile.urls',
        namespace='profile', app_name='userprofile')),


    url('', include('django.contrib.auth.urls', namespace='auth')),

    url(r'^comments/', include('django_comments.urls')),

    url(r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')),

    url(r'^(?P<url>.*/)$', views.flatpage),

]

mark2cure/userprofile/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$',
        views.settings, name='settings'),

    url(r'^points/$',
        views.user_points, name='points'),

    # Public routes
    url(r'^(?P<username>[\w.@+-]+)/edit/',
        views.settings, name='settings'),

    url(r'^(?P<username>[\w.@+-]+)/',
        views.public_profile, name='public-profile'),

]

mark2cure/team/views.py
from django.template.response import TemplateResponse
from django.shortcuts import get_object_or_404

from ..userprofile.models import Team


def home(request, slug):
    team = get_object_or_404(Team, slug=slug)
    members = team.userprofile_set.select_related('user')
    ctx = {'team': team, 'members': members}
    return TemplateResponse(request, 'team/public-team.html', ctx)

mark2cure/team/templates/team/public-team.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load humanize %}

{% block header %}
{% include "includes/header.html" %}
{% endblock %}

{% block content %}
<div id="team-profile" class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1 class="text-center">Team {{team.name|escape}}</h1>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-8 text-center">
      <div class="card">
        <div class="card-header">Description
        </div>
        <div class="card-block">{{team.description|escape}}

        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-center my-3">
    <div class="col-6">
      <div class="card">
        <div class="card-header">Quick Stats
        </div>
        <div class="card-block">
          <div class="row">
            {% if  members %}
            <div class="col-6">
              <ol class="list-unstyled">
                <li>Total Contributions: {{team.total_annotations.count|intcomma|escape}}</li>
                <li>Total Docs: {{team.total_documents.count|intcomma|escape}}</li>
                <li>Quests Finished: {{team.finished_quests.count|intcomma|escape}}</li>
                <li>Lifetime Score: {{team.total_score|intcomma|escape}}</li>
              </ol>
            </div>
            {% else %}
            <p>There are no members in this group, so there are no contributions</p>{% endif %}
            <div class="col-6">
              <ol class="list-unstyled">
                {% if  members %}
                {%  with user=team.last_active_user %}
                <li>
                  <p>Last Active User:<a href="{% url "userprofile:public-profile" username=user.username %}">{% if  user.username %}{{user.username|escape}}
                {% endif %}</a>
                  </p>
                </li>
                {% endwith %}
                <li>
                  {% if  members %}
                  <p>Last Member Activity: {{user.userprofile.last_seen|naturaltime|escape}}</p>
                  {% endif %}
                </li>
                {% endif %}
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">About
            </div>
            <div class="card-block">
              <ol class="list-unstyled">
                <li>
                  <p>Created: {{team.created|naturaltime|escape}}</p>
                </li>
                <li>
                  <p>Created by:<a href="{% url "userprofile:public-profile" username=team.owner.username %}"> {{team.owner|escape}}</a>
                  </p>
                </li>
                <li>{% if  members %}<p>Members: {{team.members_count|escape}}</p>{% endif %}
                </li>
                <li>
                  {% if  members %}
                  {%  with userprofile=team.userprofile_set.last %}
                  <p>Newest Member:<a href="{% url "userprofile:public-profile" username=userprofile.user.username %}"> {{userprofile.user.username|escape}}</a>
                  </p>
                  {% endwith %}
                  {% endif %}
                </li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% if  members %}
  <div class="row justify-content-center my-3">
    <div class="col-10">
      <div class="card">
        <div class="card-header">Members
        </div>
        <div class="card-block">
          <div class="row">
            {% for member_profile in members %}
            <div class="col-4"><a href="{% url "userprofile:public-profile" username=member_profile.user.username %}">
                <p class="lead text-xs-center">{{member_profile.user.username|escape}}</p></a>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endif %}
</div>
{% endblock %}