mark2cure/instructions/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView


urlpatterns = [

    # Entity Recognition Task Specific
    url(r'^entity-recognition/disease-marking/$',
        TemplateView.as_view(template_name='instructions/tasks/ner/diseases.html'),
        name='entity-recognition-diseases'),

    url(r'^entity-recognition/gene-marking/$',
        TemplateView.as_view(template_name='instructions/tasks/ner/genes.html'),
        name='entity-recognition-genes'),

    url(r'^entity-recognition/treatment-marking/$',
        TemplateView.as_view(template_name='instructions/tasks/ner/treatments.html'),
        name='entity-recognition-treatments'),

    url(r'^entity-recognition/$',
        TemplateView.as_view(template_name='instructions/tasks/ner/home.html'),
        name='entity-recognition'),

    # Relation Task Specific
    url(r'^relation/definition/disease/$',
        TemplateView.as_view(template_name='instructions/tasks/re/disease-concept.html'),
        name='relation-definition-disease'),

    url(r'^relation/definition/gene/$',
        TemplateView.as_view(template_name='instructions/tasks/re/gene-concept.html'),
        name='relation-definition-gene'),

    url(r'^relation/definition/drug/$',
        TemplateView.as_view(template_name='instructions/tasks/re/drug-concept.html'),
        name='relation-definition-drug'),

    url(r'^relation/gene-disease/$',
        TemplateView.as_view(template_name='instructions/tasks/re/gene-disease-relation.html'),
        name='relation-gene-disease'),

    url(r'^relation/drug-disease/$',
        TemplateView.as_view(template_name='instructions/tasks/re/drug-disease-relation.html'),
        name='relation-drug-disease'),

    url(r'^relation/gene-drug/$',
        TemplateView.as_view(template_name='instructions/tasks/re/gene-drug-relation.html'),
        name='relation-gene-drug'),

    url(r'^relation/$',
        TemplateView.as_view(template_name='instructions/tasks/re/home.html'),
        name='relation'),

    url(r'', TemplateView.as_view(template_name='instructions/home.html'), name='home'),
]

mark2cure/urls.py
from django.conf.urls import include, url

from django.contrib import admin
from django.contrib.flatpages import views
from django.contrib.auth import views as reset_views

from django.contrib.sitemaps import Sitemap
from django.contrib.sitemaps.views import sitemap
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.urls import reverse

from django.contrib.auth.models import User
from mark2cure.common.models import Group
from mark2cure.userprofile.models import Team


class FlatPages(FlatPageSitemap):
    protocol = 'https'
    priority = 1.0
    changefreq = 'monthly'


class QuestDetails(Sitemap):
    protocol = 'https'
    priority = 1.0
    changefreq = 'weekly'

    def items(self):
        return Group.objects.values_list('stub', flat=True)

    def location(self, item):
        return reverse('common:ner-group-home', kwargs={'group_stub': item})


class UserDetails(Sitemap):
    protocol = 'https'
    priority = .5
    changefreq = 'weekly'

    def items(self):
        return User.objects.values_list('username', flat=True)

    def location(self, item):
        return reverse('profile:public-profile', kwargs={'username': item})


class TeamDetails(Sitemap):
    protocol = 'https'
    priority = .6
    changefreq = 'weekly'

    def items(self):
        return Team.objects.values_list('slug', flat=True)

    def location(self, item):
        return reverse('team:home', kwargs={'slug': item})


sitemaps = {
    'flatpages': FlatPages,
    'quest_detail': QuestDetails,
    'user_detail': UserDetails,
    'team_detail': TeamDetails
}

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    # url(r'^robots\.txt', include('robots.urls')),

    # Password / Account based changes
    url(r'^accounts/', include('mark2cure.userprofile.providers.zooniverse.urls')),
    url(r'^accounts/', include('allauth.urls')),

    # Response / Confirm Changes
    url(r'^reset/done/$',
        reset_views.password_reset_complete,
        {'template_name': 'password-reset/password_reset_complete.html'},
        name='reset'),

    url(r'^reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        reset_views.password_reset_confirm,
        {'template_name': 'password-reset/password_reset_confirm.html',
         'post_reset_redirect': '/reset/done/'},
        name='password_reset_confirm'),

    url(r'', include('mark2cure.common.urls',
        namespace='common')),

    url(r'^api/', include('mark2cure.api.urls',
        namespace='api')),

    url(r'^download/', include('mark2cure.download.urls',
        namespace='download')),

    url(r'^instructions/', include('mark2cure.instructions.urls',
        namespace='instructions')),
    url(r'^training/', include('mark2cure.training.urls',
        namespace='training')),


    # Task Section
    url(r'^task/ner/', include('mark2cure.task.ner.urls',
        namespace='task-ner')),

    url(r'^task/re/', include('mark2cure.task.re.urls',
        namespace='task-re')),

    url(r'^talk/', include('mark2cure.talk.urls',
        namespace='talk')),

    url(r'^team/', include('mark2cure.team.urls',
        namespace='team', app_name='team')),
    url(r'^u/', include('mark2cure.userprofile.urls',
        namespace='profile', app_name='userprofile')),


    url('', include('django.contrib.auth.urls', namespace='auth')),

    url(r'^comments/', include('django_comments.urls')),

    url(r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')),

    url(r'^(?P<url>.*/)$', views.flatpage),

]

mark2cure/instructions/templates/instructions/chemical-disease-relation.html
<!DOCTYPE html>
<meta charset="utf-8">
<style>

.node rect {
  cursor: pointer;
  fill: #fff;
  fill-opacity: 0.7;
  stroke: #333;
  stroke-width: 2px;
}

.node text {
  font: 22px sans-serif;
  pointer-events: none;
}

path.link {
  fill: none;
  /*stroke: #333;*/
  stroke-width: 2px;
}
div.tooltip {
  position: absolute;
  text-align: left;
  width: 500px;
  /*height: 120px;*/
  padding: 20px;
  font: 20px sans-serif;
  background: #ddd;
  border: solid 4px #aaa;
  border-radius: 8px;
  pointer-events: none;
}
p.paragraph span.user_annotated_green,
span.user_annotated_green {
  background-color: #B1FFA8;
}

</style>
<body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>

// var test_width = 0;
//
// $(document).ready(function(){
//   test_width = $(document).width();
//     $(window).resize(function(){
//         console.log("hello");
//         console.log($(document).width());
//         console.log($(window).width());
//         test_width = $(document).width();
//         update(root);
//     return test_width;
//     });
// });

var margin = {top: 50, right: 20, bottom: 20, left: 20},
    width = 1400 - margin.left - margin.right,
    barHeight = 60,
    barWidth = width * .45;

var i = 0,
    duration = 550,
    root;

var tree = d3.layout.tree()
    .nodeSize([0, 20]);

var diagonal = d3.svg.diagonal()
    .projection(function(d) { return [d.y, d.x]; });

var svg = d3.select("body").append("svg:svg")
    .attr("width", width + margin.left + margin.right)
    .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

root = {
  "id": "1-1-1-1-1-1",
  "text": "Chemical + Disease Relationship",
  "desc": "Chemical + Disease relationship definitions",
  "example": "Hover over items for more information.",
  "children": [{
    "id": "1",
    "text": "(chemical) relates to disease",
    "desc": "The chemical has some type of relation to the disease.",
    "example": "Evidence indicates that Amblyomin-X could be a promising candidate for cancer therapy.",
    "children": [{
        "id": "1-2",
        "text": "Exacerbates",
        "desc": "The chemical worsens or exacerbates the disease in any manner.",
        "example": "St. John's Wort has been known to worsen symptoms of Parkinson's disease.",
      }, {
        "id": "1-1",
        "text": "Treats",
        "desc": "The chemical improves or treats the disease in any manner.",
        "example": "Treatment with gingerol may provide a novel therapeutic strategy for prion-mediated neurotoxicity",
      }, {
        "id": "1-3",
        "text": "Increases risk of disease",
        "desc": "Administration of the drug increases chances of getting the disease. Considered an 'adverse side effect' of the drug.",
        "example": "Parkinson's disease risk factors include ageing, exposure to toxins and genetic defects.",
      }, {
        "id": "1-4",
        "text": "May cause",
        "desc": "Administration of the chemical may cause or lead to the disease.",
        "example": "43% of mice given the chemical NVP-BHG712 developed pulmonary metastases.",
      }, {
        "id": "1-5",
        "text": "Prevents",
        "desc": "Administration of the chemical prevents the disease",
        "example": "Malarone is taken daily by travelers wanting to prevent malaria.",
      }]
    }, {
    "id": "2",
    "text": "has no relation to",
    "desc": "There is no relation between the chemical and disease.",
    "example": "To study soft tissue sarcoma, an experimental group of mice was given the chemical NVP-BHG712.",
        }]
}


function update(source) {

  // Compute the flattened node list. TODO use d3.layout.hierarchy.
  var nodes = tree.nodes(root);

  var height = Math.max(500, nodes.length * barHeight + margin.top + margin.bottom);

  d3.select("svg").transition()
      .duration(duration)
      .attr("height", height * 1.5);

  d3.select(self.frameElement).transition()
      .duration(duration)
      .style("height", height + "px");

  // Compute the "layout".
  nodes.forEach(function(n, i) {
    n.x = i * (barHeight * 1.3);
  });

  // Update the nodes…
  var node = svg.selectAll("g.node")
      .data(nodes, function(d) { return d.pid || (d.pid = ++i); });


  var nodeEnter = node.enter().append("g")
      .attr("class", "node")
      .attr("transform", function(d) { return "translate(" + source.y0 + "," + source.x0 + ")"; })
      .style("opacity", 1e-6);



  // COPIED from http://bl.ocks.org/mbostock/1087001
  var div = d3.select("body").append("div")
      .attr("class", "tooltip")
      .style("opacity", 1e-6);

  nodeEnter.append("rect")
      .attr("y", -barHeight / 2)
      .attr("x", indent_of)
      .attr("height", barHeight)
      .attr("width", barWidth)
      .style("fill", color)
      // .on("click", click)
      .on("mouseover", function() {
      div.attr("class", "tooltip").transition()
          .duration(0)
          .style("opacity", 1);
        }
    )
      .on("mousemove", function(d) {
        div
            .style("left", (d3.event.pageX + 10) + "px")
            .style("top", (d3.event.pageY - 12) + "px")
            .html("<h3>Definition:</h3>" + d.desc + "<h3>Example:</h3>" + d.example);
      })
      .on("mouseout", function() {
      div.attr("class", "tooltip")
          .transition()
          .duration(500)
          .style("opacity", 1e-6);
        }
    );

  nodeEnter.append("text")
      .attr("dy", -3)
      .attr("dx", function(obj) { return indent_of(obj)+20; })
      .text(function(d) {
        var my_text = "   " + d.text;
        return my_text;
      });

  // Transition nodes to their new position.
  nodeEnter.transition()
      .duration(duration)
      .attr("transform", function(d) { return "translate(" + d.y + "," + d.x + ")"; })
      .style("opacity", 1);

  node.transition()
      .duration(duration)
      .attr("transform", function(d) { return "translate(" + d.y + "," + d.x + ")"; })
      .style("opacity", 1)
      .select("rect")
      .style("fill", color);

  // Transition exiting nodes to the parent's new position.
  node.exit().transition()
      .duration(duration)
      .attr("transform", function(d) { return "translate(" + source.y + "," + source.x + ")"; })
      .style("opacity", 1e-6)
      .remove();

  // Update the links…
  var link = svg.selectAll("path.link")
      .data(tree.links(nodes), function(d) { return d.target.id; });

  // Enter any new links at the parent's previous position.
  link.enter().insert("path", "g")
      .attr("class", "link")
      .attr("d", function(d) {
        var o = {x: source.x0, y: source.y0};
        return diagonal({source: o, target: o});
      })
    .transition()
      .duration(duration)
      .attr("d", diagonal);

  // Transition links to their new position.
  link.transition()
      .duration(duration)
      .attr("d", diagonal);

  // Transition exiting nodes to the parent's new position.
  link.exit().transition()
      .duration(duration)
      .attr("d", function(d) {
        var o = {x: source.x, y: source.y};
        return diagonal({source: o, target: o});
      })
      .remove();

  // Stash the old positions for transition.
  nodes.forEach(function(d) {
    d.x0 = d.x;
    d.y0 = d.y;
  });
}



update(root);



// Toggle children on click.
function click(d) {
  if (d.children) {
    d._children = d.children;
    d.children = null;
  } else {
    d.children = d._children;
    d._children = null;
  }
  update(d);
}

function indent_of(d) {
  var my_string = d.id;
  if (my_string.length === 1) {
    indent = 100;
  } else if (my_string.length === 3) {
    indent = 150;
  } else if (my_string.length === 5) {
    indent = 200;
  } else {
    indent = 0;
}
return indent;
};


function color(d) {
  var my_string = d.id;
  if (my_string.length === 1) {
    return "#9e9ac8";
  } else if (my_string.length === 3) {
      return "#6a51a3";
  } else if (my_string.length === 5) {
      return "#3f007d";
  } else {
    return "#dadaeb";
  }
};




</script>

mark2cure/instructions/templates/instructions/home.html
{% extends "base.html" %}

{% block header %}
{%  with headerMessage='Instructions' %}
{% include "includes/header.html" %}
{% endwith %}
{% endblock %}

{% block content %}
<div id="instructions" class="content container mt-1 mb-2">
  <div class="row">
    <div class="col">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url "instructions:home" %}">Instructions</a></li>
        {% block breadcrumb %}{% endblock %}
      </ol>
    </div>
  </div>
  <div class="row">
    <div id="sidebar-navigation" class="col-md-3">{% include "instructions/sidebar.html" %}
    </div>
    <div class="col-md-9">
      {% block instructions-content %}
      <p class="lead text-xs-center m-t-2">There are many rules to follow in Mark2Cure, the instructions portal is intended to provide an up to date reference guide for how to properly perform Mark2Cure tasks.</p>
      {% endblock %}
    </div>
  </div>
</div>
{% endblock %}

mark2cure/instructions/templates/instructions/sidebar.html
<h4 class="text-center mb-3"><a href="{% url "instructions:entity-recognition" %}">Entity Recognition Task</a></h4>
<div class="list-group"><a href="{% url "instructions:entity-recognition-diseases" %}" class="list-group-item">Diseases</a><a href="{% url "instructions:entity-recognition-genes" %}" class="list-group-item">Genes</a><a href="{% url "instructions:entity-recognition-treatments" %}" class="list-group-item">Treatments</a></div>

<h4 class="text-center my-3"><a href="{% url "instructions:relation" %}">Relation Task</a></h4>
<div class="list-group"><a href="{% url "instructions:relation-definition-disease" %}" class="list-group-item">Disease Definition</a><a href="{% url "instructions:relation-definition-gene" %}" class="list-group-item">Gene Definition</a><a href="{% url "instructions:relation-definition-drug" %}" class="list-group-item">Drug Definition</a>
  <hr/><a href="{% url "instructions:relation-gene-disease" %}" class="list-group-item">Gene <i class="fa fa-angle-right" aria-hidden="true"></i> Disease</a><a href="{% url "instructions:relation-drug-disease" %}" class="list-group-item">Drug <i class="fa fa-angle-right" aria-hidden="true"></i> Disease</a><a href="{% url "instructions:relation-gene-drug" %}" class="list-group-item">Gene <i class="fa fa-angle-right" aria-hidden="true"></i> Drug</a>
</div>